[package]
name = "c_scrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.3.1"
reqwest = { version ="0.12.23", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.142"
url = "2.5.4"
